# Generated by Django 5.0.3 on 2024-03-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_1',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('balance', models.IntegerField(db_column='balance')),
                ('lim', models.IntegerField(db_column='lim')),
                ('status', models.CharField(db_column='status', max_length=255)),
                ('type_face', models.CharField(db_column='type_face', max_length=255)),
                ('payments', models.CharField(db_column='payments', max_length=255)),
                ('expenses', models.IntegerField(db_column='expenses')),
                ('services', models.CharField(db_column='services', max_length=255)),
                ('adjustment', models.CharField(db_column='adjustment', max_length=255)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
    ]
