# Generated by Django 5.0.3 on 2024-03-31 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_1',
        ),
    ]
